name: growmate_machine_hiring_platform
description: GrowMate Harvester Machine Hiring Platform
publish_to: 'none' # since this is a local project

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^6.1.1
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/rice1.jpg
    - assets/images/rice2.jpg
    - assets/images/rice3.jpg
    - assets/images/rice4.jpg
    - assets/images/rice5.jpg
    - assets/images/rice6.jpg
    - assets/images/rice7.jpg
    - assets/images/rice8.jpg
    - assets/images/rice9.jpg
    - assets/images/rice10.jpg
    - assets/images/corn1.jpg
    - assets/images/corn2.jpg
    - assets/images/corn3.jpg
    - assets/images/corn4.jpg
    - assets/images/corn5.jpg
    - assets/images/corn6.jpg
    - assets/images/corn7.jpg
    - assets/images/corn8.jpg
    - assets/images/corn9.jpg
    - assets/images/corn10.jpg
    